### ISSUE TITLE
Naviter documentation missing

### ISSUE THREAD

**Issue by akolar** [glidernet/ogn-aprs-protocol#1]
I'm opening this issue more as a formality than anything else. I'll be doing a pull request that adds a document with the specification of Naviter's APRS message format in a moment.

If there is anything vague about the format (or our implementation of it), feel free to comment on this issue and we'll try our best to update the document with a beter explanation.

**Comment by akolar** [comment]
First, thanks for reminding us about the special format for the relayed messages.


Before I commit the changes, I just want to make sure, what should we considered as a relay:

**Case 1:**
An Oudie is transmiting its own location through Oudie Live. Naviter serves as a intermediary between the Oudie and the APRS network.

Such messages should be formatted using the standard format:
`NAVxxxxxx>OGNAVI,qAS,NAVITER...`

**Case 2:**
An Oudie is connected to a Flarm device using a serial/bluetooth connection. Oudie is transmiting Flarms' location through Oudie Live to Naviter and we broadcast it to the OGN.

**Case 3:**
An Oudie is transmiting its and the location of all other Flarms in range (again via Oudie Live to Naviter and then to the OGN).

Messages from cases 2 and 3 should be using the relay format which you described above; that is:

`FLRxxxxxx>OGNAVI,NAVyyyyyy*,qAS,NAVITER...`


Is this correct or should we also be using the standard syntax in the second case?

Thanks,
Anze

**Comment by acasadoalonso** [comment]
Anze,

IMHO cases 2 and 3 are the same, in both cases you are transmitting information that you are RELAYing from a different source, regardless if the device RELAYing is on the same glider or several kilometers away ....

I am copying Hessu and Pawel that have more experience than myself.
Thanks for your contribution.

AC/.

**Comment by akolar** [comment]
Hi Angel.

Great, thanks for all the info! I'll wait for the input from Hessu and Pawel before creating another PR with the updated specs.

Anze

**Comment by pjalocha** [comment]
What you describe is fine I believe.
NAVyyyyyy* means the message has been relayed by the NAVyyyyyy - the star
"*" means "has already been relayed" - no star is a request to relay it
through the specified relay.

This is as far, as my APRS understanding goes, Heikki could confirm.

Pawel

**Comment by pjalocha** [comment]
An alternative could be "object report" as in Chapter 11 of the
specification http://www.aprs.org/doc/APRS101.PDF, but I believe relay (or
digipeat in APRS wording) is simpler.

**Comment by akolar** [comment]
Paweł, thanks for your reply. 

After reading the section on object reports I also belive, that sticking to the first format would be better.
Adding another field in the message header doesn't add much complexity to the existing format, whereas the object report format would require a completely different parser.

Here's an example:
Relayed message: `FLRFFFFFF>OGNAVI,NAVABCDEF*,qAS,NAVITER:/092002h1000.00S/01000.00W'000/000/
A=003281 !W00! id2820FFFFFF +300fpm +1.7rot` 
Object report (example copied from the docs, no comment field is set): `;LEADER*092345z4903.50N/07201.75W>088/036 `

Additionaly, the APRS specs state that "[object reports are] intended for situations
where the entity is not capable of reporting its own position". This will not necessarily hold true for relayed messages.

For the reasons listed -- if you, Heikki and Angel all agree -- I'd prefer to use the relay message format. 

Anze

**Comment by acasadoalonso** [comment]
Anze,
I would recommend the relay message as well.
Go ahead with the PR.
Cheers. 

AC/.

**Comment by akolar** [comment]
Angel, Paweł, once again, thank you both for your inputs on this matter. :)
I've created another PR with the fixed format and I hope there is no more issues with the rest of the document.

Anze
