### ISSUE TITLE
Check sample beacons for InReach protocol

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-aprs-protocol#10]
The sample beacons for InReach protocol looks like this:
`OGN8A0749>OGINREACH,qAS,INREACH:/142700h0448.38N/07600.74W'000/000/A=004583 id300434060496190 inReac True`

But we get beacons with different dstcall (OGINRE instead of OGINREACH) and more fields.
```
OGN8A0749>OGINRE,qAS,INREACH:/154200h5115.68N/00005.57W'000/000/A=000600 id300434060496190 inReac True Ian Lewis
FLRA666CE>OGINRE,qAS,INREACH:/234700h3909.62N/12207.94W'000/000/A=000045 id300434062719880 inReac True Philip Lee
```

**Comment by acasadoalonso** [comment]
Fixed now

AC/.

**Comment by acasadoalonso** [comment]
Fixed ... thanks for your cooperation
