### ISSUE TITLE
Unknown beacon type "OGPAW"

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-aprs-protocol#7]
Not supported beacon type, skipped: ICA404EC3>OGPAW,qAS,UKWOG:/104337h5211.24N\00032.65W^124/081/A=004026 !W62! id21404EC3 12.5dB +2.2kHz
Not supported beacon type, skipped: ICA404EC3>OGPAW,qAS,UKWOG:/104341h5211.18N\00032.53W^131/081/A=004010 !W85! id21404EC3 9.2dB +2.2kHz  #+10.0dBm

**Comment by pjalocha** [comment]
It is the PilotAware received by an OGN ground receiver.

**Comment by acasadoalonso** [comment]
I will add the documentation to the git repo 
Thx

AC/.

**Comment by acasadoalonso** [comment]
Fixed, add the PilotAware APRS messages
